services:
  db:
    image: postgres:latest
    container_name: saas-db-compose
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata_saas:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - saas-network

  backend:
    build: ./backend/SaasApi
    container_name: saas-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s        # Testa a cada 10 segundos
      timeout: 5s          # Se demorar mais de 5s, falha
      retries: 3           # Falhou 3x seguidas? Marca como Unhealthy
      start_period: 10s    # Dá 10s de folga pro container subir antes de começar a testar
    
    depends_on:
      db:
        condition: service_started  
        
    networks:
      - saas-network

  web:
    image: nginx:latest
    container_name: saas-proxy-compose
    ports:
      - "8080:80"
    networks:
      - saas-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000" # Porta de acesso ao painel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Permite que ele "controle" o Docker do seu PC
      - portainer_data:/data # Salva suas configurações e senha

volumes:
  pgdata_saas:
  portainer_data:

networks:
  saas-network:
