services:
  - type: web
    name: saas-backend
    env: docker
    region: ohio
    plan: free
    branch: main
    dockerfilePath: backend/SaasApi/Dockerfile

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Gemini__ModelId
        value: gemini-flash-latest
      - key: Gemini__ApiKey
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false